'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class filtros

    '''<summary>
    '''ASPxAdministracion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxAdministracion As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxReportes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxReportes As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxReportes_aerop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxReportes_aerop As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ASPxComboBox_cias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_cias As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxDateEdit_fechainicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxDateEdit_fechainicio As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxComboBox_tipo_formulario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_tipo_formulario As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxComboBox_aerop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_aerop As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxDateEdit_fechafin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxDateEdit_fechafin As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxButton9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton9 As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''SqlDataSource_aerodrome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_aerodrome As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_cias_filtro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_cias_filtro As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataTipoFormulario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataTipoFormulario As Global.System.Web.UI.WebControls.SqlDataSource
End Class
